name: todo_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.1.7

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/


  fonts:
    - family: Boldonse
      fonts:
        - asset: assets/fonts/Boldonse-Regular.ttf
    - family: Tektur
      fonts:
        - asset: assets/fonts/Tektur-VariableFont_wdth,wght.ttf
  

